app:
  allowed_exts:
    - .txt
    - .md
    - .csv
    - .json
    - .yaml
    - .yml
    - .html
    - .xml
    - .docx
    - .xlsx
    - .pptx
    - .pdf
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .bmp
    - .py
    - .js
    - .ts
    - .java
    - .kt
    - .scala
    - .cs
    - .cpp
    - .go
    - .php
    - .swift
    - .r
    - .pl
    - .sql
    - .sh
    - .zsh
    - .bash
  docs_dir: ./documents
  max_file_preview_size: 1048576