DEFAULT_FILE_PATH = "/app/documents"
DEFAULT_FILENAME_WO_EXT = "test"
DEFAULT_FILE_EXT = "txt"
DEFAULT_FILENAME_WITH_EXT = f"{DEFAULT_FILENAME_WO_EXT}.{DEFAULT_FILE_EXT}"
DEFAULT_FILE_CONTENT: bytes = b"test content"
DEFAULT_FILE_CONTENT_TYPE = "text/plain"

LARGE_FILE_SIZE = 10 * 1024 * 1024
LONG_FILENAME_LENGTH = 200
