DEFAULT_FILELIST_PATH = ""
DEFAULT_FILELIST_FILE_BASE_NAME = "document"
DEFAULT_FILELIST_FILE_EXT = "txt"
DEFAULT_FILELIST_FILE_SIZE = 100

DEFAULT_PAGINATION_CURRENT_PAGE = 1
DEFAULT_PAGINATION_TOTAL_PAGES = 2
DEFAULT_PAGINATION_FILES_ON_PAGE = 10
DEFAULT_PAGINATION_TOTAL_FILES = 15

DEFAULT_PAGINATION_PAGE = 2
DEFAULT_PAGINATION_LIMIT = 10

EXPECTED_FILELIST_SORT_FIELDS = ["name", "ext", "size", "created_at"]
EXPECTED_FILELIST_SORT_ORDERS = ["asc", "desc"]
EXPECTED_FILELIST_FILTER_EXTENSIONS = ["txt", "docx", "pdf", "png"]

DEFAULT_FILELIST_FILTER_EXT = "docx"

MAX_FILELIST_LIMIT = 100

INVALID_FILELIST_PARAM_VALUE = "wrong"
