DEFAULT_RAG_PROVIDER = "ollama"
DEFAULT_RAG_MODEL = "test rag model"
DEFAULT_RAG_TOP_K = 3
DEFAULT_RAG_SIMILARITY_THRESHOLD = 0.5
DEFAULT_RAG_PATH = "./test_rag_path"
DEFAULT_RAG_USE_VECTOR_DB = False
DEFAULT_RAG_USE_LOCAL_VECTOR_DB = False
